### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by epony4c** [y1nglamore/IDOR_detect_tool#6]
大佬，这种目标是IP的，需要加协议跟端口吗？
例如这么写对吗?
![image](https://user-images.githubusercontent.com/17228839/224205669-a21723c4-c9f5-4488-b621-4ae302354a0a.png)

**Comment by y1nglamore** [comment]
加端口应该不太行，是个小bug，因为我只匹配了pretty_host，没有匹配port，后面改下

**Comment by y1nglamore** [comment]
已更新port的匹配

**Comment by epony4c** [comment]
666
